#!/usr/bin/env ruby

Dir["#{File.dirname(__FILE__)}/etc/*"].each do |target|
  target_path = File.expand_path(target)
  dest_path = File.expand_path("~/.#{File.basename(target)}")

  cmd = "ln -nsf --backup %s %s" % [target_path, dest_path]
  system(cmd)
end

