#!/bin/bash

cd "$(dirname "$0")"
stow --adopt */

# --adopt will cause any conflicting files to modify the versions of the dot
# files in the dotfiles checkout.  This is most likely something we care about,
# so stash them away to get back to the state that was checked in.
if [[ -n $(git status -s) ]]; then
    git stash
fi
