if &compatible
  set nocompatible
endif
set runtimepath+=~/.nvim/bundle/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.nvim/bundle')
    call dein#begin('~/.nvim/bundle')

    " Let dein manage dein
    call dein#add('Shougo/dein.vim')

    " Navigation
    call dein#add('mileszs/ack.vim.git')
    call dein#add('justinmk/vim-dirvish')
    call dein#add('ctrlpvim/ctrlp.vim')
    call dein#add('ludovicchabant/vim-gutentags')

    " Git
    call dein#add('airblade/vim-gitgutter.git')
    call dein#add('fatih/vim-go')
    call dein#add('tpope/vim-fugitive')

    " Appearance
    call dein#add('frankier/neovim-colors-solarized-truecolor-only')
    "call dein#add('altercation/vim-colors-solarized.git')
    call dein#add('flazz/vim-colorschemes')
    call dein#add('justinmk/molokai')
    call dein#add('nanotech/jellybeans.vim')
    call dein#add('nathanaelkane/vim-indent-guides.git')
    call dein#add('vim-airline/vim-airline-themes')
    call dein#add('bling/vim-airline')
    call dein#add('morhetz/gruvbox')
    call dein#add('romainl/flattened')
    call dein#add('whatyouhide/vim-gotham')
    call dein#add('NLKNguyen/papercolor-theme')
    call dein#add('rakr/vim-one')
    call dein#add('rakr/vim-two-firewatch')
    call dein#add('mhartington/oceanic-next')

    " Build
    call dein#add('benekastah/neomake')
    "call dein#add('w0rp/ale')

    " Editing
    call dein#add('ntpeters/vim-better-whitespace.git')
    call dein#add('tpope/vim-surround')
    call dein#add('michaeljsmith/vim-indent-object')
    call dein#add('AndrewRadev/splitjoin.vim')
    call dein#add('wellle/targets.vim')
    call dein#add('justinmk/vim-sneak')
    call dein#add('tpope/vim-unimpaired')
    call dein#add('FooSoft/vim-argwrap')

    " File Types
    call dein#add('google/vim-jsonnet')

    " AutoCompletion
    if has("nvim")
        call dein#add('Shougo/deoplete.nvim')
        call dein#add('zchee/deoplete-go', {'build': 'make'})
        "call dein#add('Shougo/neosnippet')
        "call dein#add('Shougo/neosnippet-snippets')
    endif

    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable

" colorscheme overrides. has to be before any colorscheme lines
augroup colorscheme_overrides
    autocmd!
    "autocmd ColorScheme * highlight Search cterm=underline ctermfg=217 ctermbg=16 gui=underline guifg=#f0a0c0 guibg=#302028
    autocmd ColorScheme * highlight Search cterm=underline ctermfg=217 ctermbg=16 gui=underline guifg=#f0a0c0 guibg=NONE
augroup END

if has("gui")
    " Start without the toolbar
    set guioptions-=T
    " Start without the right toolbar
    set guioptions-=r
    set guioptions-=R
    " Start without the left toolbar
    set guioptions-=l
    set guioptions-=L
endif

if has("gui_macvim")
    set guifont=Knack\ Nerd\ Font:h13

    colorscheme one
    set background=light

    " Fullscreen takes up entire screen
    set fuoptions=maxhorz,maxvert

    " Map Command-# to switch tabs
    map  <D-0> 0gt
    imap <D-0> <Esc>0gt
    map  <D-1> 1gt
    imap <D-1> <Esc>1gt
    map  <D-2> 2gt
    imap <D-2> <Esc>2gt
    map  <D-3> 3gt
    imap <D-3> <Esc>3gt
    map  <D-4> 4gt
    imap <D-4> <Esc>4gt
    map  <D-5> 5gt
    imap <D-5> <Esc>5gt
    map  <D-6> 6gt
    imap <D-6> <Esc>6gt
    map  <D-7> 7gt
    imap <D-7> <Esc>7gt
    map  <D-8> 8gt
    imap <D-8> <Esc>8gt
    map  <D-9> 9gt
    imap <D-9> <Esc>9gt
endif


if has("nvim")
    set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor

    " makes neovim use gui colors in themes instead of cterm colors, usually
    " this is only useful with a tmux and iterm2 both capable of displaying
    " 24bit "True" color
    set termguicolors

    " let g:two_firewatch_italics=1
    "colorscheme two-firewatch
    "set background=dark

    "colorscheme one
    "set background=dark

    "colorscheme PaperColor
    "set background=light

    " let g:rehash256 = 1
    " let g:molokai_original = 1
    "colorscheme molokai
    "set background=dark

    " colorscheme jelleybeans
    " set background=light

    " set background=dark
    " colorscheme kalisi

    "colorscheme Tomorrow-Night
    "set background=dark

    "let g:gruvbox_italic=1
    "let g:gruvbox_contrast_dark="medium"
    "set background=dark
    "colorscheme gruvbox

    colorscheme OceanicNext
    set background=dark
    let g:airline_theme='oceanicnext'

    " built-in terminal navigation
    tnoremap <A-h> <C-\><C-n><C-w>h
    tnoremap <A-j> <C-\><C-n><C-w>j
    tnoremap <A-k> <C-\><C-n><C-w>k
    tnoremap <A-l> <C-\><C-n><C-w>l
    nnoremap <A-h> <C-w>h
    nnoremap <A-j> <C-w>j
    nnoremap <A-k> <C-w>k
    nnoremap <A-l> <C-w>l

    " Deoplete config
    let g:deoplete#enable_at_startup = 1
    " neocomplete like
    set completeopt+=noinsert
    " deoplete.nvim recommend
    set completeopt+=noselect
    " disable preview scratch buffer
    set completeopt-=preview

    " Neomake configuration
    let g:neomake_python_flake8_maker = {
        \ 'args': ['--format=default', '--ignore=E261,E302,E402,E501,E731'],
        \ 'errorformat':
            \ '%E%f:%l: could not compile,%-Z%p^,' .
            \ '%A%f:%l:%c: %t%n %m,' .
            \ '%A%f:%l: %t%n %m,' .
            \ '%-G%.%#',
        \ 'postprocess': function('neomake#makers#ft#python#Flake8EntryProcess')
        \ }
    let g:neomake_python_enabled_makers = ['flake8']
    let g:neomake_go_enabled_makers = ['go', 'gometalinter']
    "let g:neomake_go_gometalinter_args = ['--disable-all', '--enable=errcheck', '--enable=gosimple', '--enable=staticcheck', '--enable=unused']
    let g:neomake_go_gometalinter_args = ['--fast']

    " Deoplete config
    let g:deoplete#enable_at_startup = 1
    " neocomplete like
    set completeopt+=noinsert
    " deoplete.nvim recommend
    set completeopt+=noselect
    " disable preview scratch buffer
    set completeopt-=preview

endif

if !has("nvim")
    " remove the delay when pressing esc
    set noesckeys

    " cargo cult nvim defaults
    set autoindent
    set autoread
    set backspace="indent,eol,start"
    set display="lastline"
    set formatoptions="tcqj"
    set history=10000
    set nrformats="bin,hex"
    set showcmd
    set smarttab
    set tabpagemax=50
    set tags="./tags;,tags"
    set ttyfast
    set wildmenu
endif

" plain old vim
if !has("nvim") && !has("gui_macvim")
    set t_Co=256

    colorscheme jelleybeans
    set background=dark
endif

" gutentags config
let g:gutentags_ctags_exclude = ['*/go/src/vendor/*', '*/clj/external/*', '*/node_modules/*']

" vim-go
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1 " let neomake / ale show syntax errors
let g:go_updatetime = 400
let g:go_snippet_engine = 'neosnippet'

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_build_constraints = 1
let g:go_auto_sameids = 1
let g:go_auto_type_info = 1

" let g:go_highlight_functions = 1
" let g:go_highlight_methods = 1
" let g:go_highlight_extra_types = 1

" go specific keybindings
augroup filetype_go
    autocmd!
    autocmd FileType go nnoremap <buffer> <localleader>gb :GoBuild<CR>
    autocmd FileType go nnoremap <buffer> <localleader>gi :GoInstall<CR>
    autocmd FileType go nnoremap <buffer> <localleader>gt :GoTest<CR>
    autocmd FileType go nnoremap <buffer> <localleader>gc :GoCoverageToggle<CR>
    autocmd FileType go nnoremap <buffer> <localleader>gf :GoImports<CR>
    autocmd FileType go nnoremap <buffer> <localleader>gm :GoMetaLinter<CR>
    autocmd FileType go nnoremap <buffer> <localleader>gd :GoDecls<CR>
augroup END

" vim-sneak
" 2-character Sneak (don't let vim-sneak take s)
nmap f <Plug>Sneak_s
nmap F <Plug>Sneak_S
" visual-mode
xmap f <Plug>Sneak_s
xmap F <Plug>Sneak_S
" operator-pending-mode
omap f <Plug>Sneak_s
omap F <Plug>Sneak_S

" FooSoft/vim-argwrap config
let g:argwrap_tail_comma = 1
nnoremap <silent> <leader>w :ArgWrap<CR>

" For fast scrolling
"set nocursorline
"set lazyredraw
set synmaxcol=200

" Learn VimScript The Hard Way Excercises
" chapter 04
" turns current word to upper case
inoremap <C-u> <Esc>mzviwU`za
"nnoremap <C-u> mzviwU`z

" chapter 07
" edit my vimrv in a vsplit
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" source my vimrv in a vsplit
nnoremap <leader>sv :source $MYVIMRC<cr>

" chapter 09
" surround visually selected word in single quotes
vnoremap <leader>' <esc>`<i'<Esc>`>la'<esc>
" jump to beginning of line
nnoremap H ^
" jump to end of line
nnoremap L $
" scroll faster
nnoremap <C-j> 5j
nnoremap <C-k> 5k

" chapter 15
" operator pending for inside-next-paren and inside-last-paren
onoremap in( :<c-u>normal! f(vi(<cr>
onoremap il( :<c-u>normal! F)vi(<cr>
onoremap in{ :<c-u>normal! f{vi{<cr>
onoremap il{ :<c-u>normal! F}vi{<cr>

" chapter 32
" operator for :grep
nnoremap <leader>a :set operatorfunc=<sid>GrepOperator<cr>g@
vnoremap <leader>a :<c-u>call <sid>GrepOperator(visualmode())<cr>

function! s:GrepOperator(type)
    let saved_unnamed_register = @@

    if a:type ==# 'v'
        normal! `<v`>y
    elseif a:type ==# 'char'
        normal! `[v`]y
    else
        return
    endif

    execute "silent grep! " . shellescape(@@) . " ."
    copen

    let @@ = saved_unnamed_register
endfunction

" destroy add buffers
nnoremap <leader>bd :bufdo bd<cr>

" start profile
nnoremap <leader>pr :profile start /tmp/profile.log<cr>:profile func *<cr>:profile file *<cr>

" quickfix nav
nnoremap [] :cclose<cr>
nnoremap ][ :copen<cr>

" location list nav
nnoremap () :lclose<cr>
nnoremap )( :lopen<cr>

" moving selected lines
xnoremap <silent> <c-k> :move-2<CR>gv=gv
xnoremap <silent> <c-j> :move'>+<CR>gv=gv

" search for visually selected text
vnoremap <expr> // 'y/\V'.escape(@",'\').'<CR>'

" persistent undo file
set undofile

" :Silent command to supress "Press Enter to continue" messages
command! -nargs=+ Silent execute 'silent <args>' | redraw!

" bind G to grep word under cursor
" nnoremap <leader>g :Silent grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
nnoremap <M-g> :Silent grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" For vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" For vim-indent-guides
let g:indent_guides_auto_colors = 0
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2

" disable the built-in showing of mode in the command bar since airline will
" take care of that
set noshowmode

" show both absolute current line no and relative numbers
set relativenumber number

" Common typos
command! Q  quit
command! W  write
command! Wq wq


" Alt-c to copy to xclipboard. combined with ssh -X, this allows clipboard sync
" vnoremap <Esc>c :w<Home>silent <End> !xclip -in -selection clipboard<CR>
vnoremap <Esc>c Silent :w !xclip -in -selection clipboard<CR>

" Some emacs keybindings thats used all over OS X

" duplicate line / block
" nmap <C-D> yyp
" vmap <C-D> y']pgv

" delete one char in front
inoremap <C-d> <Delete>

" CtrlP customization
" leader + r -> show symbols in current buffer
nnoremap <leader>r :CtrlPBufTagAll <CR>
let g:ctrlp_cmd = 'CtrlPMRU'
" treat git root dir as the working dir
let g:ctrlp_working_path_mode = 'ra'
set wildignore+=*.pyc,*.o,*.a,*.js,*.clj,*.css,*.html
let g:ctrlp_custom_ignore='\.(pyc|o|js)'

" Show cursor position
" 2016-01-31: disabling because perf & airline shows this anyway
set noruler

" for letting swtich away from a modified buffer w/o warning
set hidden

" for highlighting search word
set hlsearch

" always show gitgutter col so text doesn't jump around when they come in
let g:gitgutter_sign_column_always=1
let g:gitgutter_realtime = 1
let g:gitgutter_eager = 1
set updatetime=150

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" Show invisible chars
set list

set title

" Always show the status line (even if no split windows)
set laststatus=2
" set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

" Number of lines to keep between cursor and window boundary before scrolling
" kicks in.
set scrolloff=7
" Number of lines to jump when scrolling. Improves rendering speed
set scrolljump=5

if has("autocmd")
    if exists(":Neomake")
        " Automatically lint files on save
        "autocmd! BufWritePost * Neomake
        augroup auto_neomake
            autocmd!
            autocmd BufWritePost *.py Neomake
            autocmd BufWritePost *.go Neomake
        augroup END
    endif

    " Automatically strip trailing whitespace
    augroup strip_whitespace
        autocmd!
        autocmd BufWritePre * if exists(":StripWhitespace") | exe "StripWhitespace" | endif
    augroup END

    " Auto-detect git commit messages
    augroup git_commit_msg
        autocmd!
        autocmd BufNewFile,BufRead COMMIT_EDITMSG set filetype=gitcommit
    augroup END

    " yaml indentation
    autocmd FileType yaml setlocal tabstop=2 expandtab shiftwidth=2 softtabstop=2
endif

" Taken from http://dotfiles.org/~defunkt/.vimrc

" don't leave hardtabs
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround

" highlight the current line
" 2016-01-32: disabling this since it slows down rendering
" set cursorline

" turn mouse on
set mouse=a
" set ttymouse=xterm2

" remap'd keys
nnoremap <Tab><Tab> <C-W>w

" Show syntax highlighting groups for word under cursor
" nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

" delete all hidden buffers
command! CloseHiddenBuffers call s:CloseHiddenBuffers()
function! s:CloseHiddenBuffers()
  let open_buffers = []

  for i in range(tabpagenr('$'))
    call extend(open_buffers, tabpagebuflist(i + 1))
  endfor

  for num in range(1, bufnr("$") + 1)
    if buflisted(num) && index(open_buffers, num) == -1
      exec "bdelete ".num
    endif
  endfor
endfunction

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --ignore=html\ --ignore=js\ --ignore=css\ --ignore=clj/\ --ignore=vendor/\ --vimgrep\ $*
  set grepformat=%f:%l:%c:%m

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g "" --ignore=js --ignore=css --ignore=clj/ --ignore=vendor/'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" backup to ~/.tmp
set backup
set backupdir=$HOME/.tmp
set writebackup

" folding settings
set foldmethod=indent
set foldlevelstart=20

" Create .swp files here to avoid git status pollution
set dir=$HOME/.tmp
"
" misc
"set ai
set incsearch
set nowrap

" Some tab helpers (<leader> is \)
map <leader>]t :tabnew<cr>
map <leader>]c :tabclose<cr>
map <leader>]m :tabmove
map <leader>]n :tabnext<cr>
map <leader>]p :tabprevious<cr>
map <leader>]` :tabfirst<cr>
map <leader>]1 1gt
map <leader>]2 2gt
map <leader>]3 3gt
map <leader>]4 4gt
map <leader>]5 5gt
map <leader>]6 6gt
map <leader>]7 7gt
map <leader>]8 8gt
map <leader>]9 9gt
map <leader>]0 :tablast<cr>

" reformat JSON
map <leader>jt  <Esc>:%!json_xs -f json -t json-pretty<CR>

" disable logipat plugin so that :E works again
let g:loaded_logipat = 1

" netrw settings
let g:netrw_liststyle=3
