export CLICOLOR=yes
export EDITOR="vim"

export PATH=/opt/local/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/mysql/bin:$PATH

export PATH=~/bin:$PATH
export PATH=$HOME/.bin:$PATH
export PATH=$HOME/.linuxbrew/bin:$PATH

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source /home/rohith/analytics/.shellenv
