source ${HOME}/.antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle gitfast
antigen bundle golang

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme amuse

# custom stuff
antigen bundle $HOME/cl/etc/oh-my-zsh-custom --no-local-clone

# Tell antigen that you're done.
antigen apply
