#zshrc, interactive shell settings
export ZSH=$HOME/.zsh
fpath=($ZSH $fpath)

# emacs integration
# [[ $EMACS = t ]] && unsetopt zle

# for tmux
# [ -n "$TMUX" ] && export TERM=screen
#
# source all files in zsh root
for include in $ZSH/*.zsh; do
  source $include
done
