<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scala</string>
	</array>
	<key>name</key>
	<string>Scala modified</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple.scala</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.scala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\n</string>
					<key>name</key>
					<string>invalid.string.newline</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.scala</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.scala.modified</string>
	<key>uuid</key>
	<string>9144dacf-0daa-4a86-979e-012e582b9b33</string>
</dict>
</plist>
