#!/bin/sh
#
# sample script to use autossh to open up a remote screen
# session, or reconnect to an existing one.
#
# $Id: rscreen,v 1.4 2002/05/07 17:54:13 harding Exp $
#
host=$1
if [ "X$host" = "X" ]; then
    host=rohith
fi

AUTOSSH_FIRST_POLL=5
AUTOSSH_POLL=10
#AUTOSSH_PORT=20000
AUTOSSH_GATETIME=5
AUTOSSH_LOGFILE=/tmp/${host}-tunnel.log
#AUTOSSH_DEBUG=yes
#AUTOSSH_PATH=/usr/local/bin/ssh
export AUTOSSH_POLL AUTOSSH_LOGFILE AUTOSSH_DEBUG AUTOSSH_PATH AUTOSSH_GATETIME AUTOSSH_PORT

autossh -f -M 0 -D 50001 -x -R2489:127.0.0.1:2489 -N $host
